// ui/src/app/workflows/components/workflow-steps/workflow-steps.tsx
import * as classNames from 'classnames';
import * as React from 'react';

import * as models from '../../../../models';

require('./workflow-steps.scss');

export interface WorkflowStepsProps {
    workflow: models.Workflow;
}

export const WorkflowSteps = (props: WorkflowStepsProps) => {
    const entryPointTemplate = props.workflow.spec.templates.find(template => template.name === props.workflow.spec.entrypoint) || {steps: [] as models.WorkflowStep[][]};
    const phase = props.workflow.status.phase;
    let isSucceeded = false;
    let isFailed = false;
    let isRunning = false;
    if (phase === models.NODE_PHASE.RUNNING) {
        isRunning = true;
    } else {
        isSucceeded = phase === models.NODE_PHASE.SUCCEEDED;
        isFailed = !isSucceeded;
    }
    const steps = (entryPointTemplate.steps || [])
        .map(group => group[0])
        .map(step => ({name: step.name, isSucceeded, isFailed, isRunning}))
        .slice(0, 3);

    return (
        <div className='workflow-steps'>
            <div className='workflow-steps__title'>
                <div className='workflow-steps__icon'>
                    <i className='ax-icon-job' aria-hidden='true' />
                </div>
                <div className='workflow-steps__description'>
                    <div className='workflow-steps__description-title'>{props.workflow.metadata.name}</div>
                </div>
            </div>
            <div className='workflow-steps__timeline'>
                <div className='workflow-steps__step-dots'>
                    <div className='workflow-steps__step-circle workflow-steps__step-circle-small' />
                    <div className='workflow-steps__step-circle workflow-steps__step-circle-small' />
                    <div className='workflow-steps__step-circle workflow-steps__step-circle-small' />
                    <div className='workflow-steps__step-name'>&nbsp;</div>
                </div>
                {steps.map(step => (
                    <div
                        key={step.name}
                        className={classNames('workflow-steps__step', {
                            'workflow-steps__step--succeeded': step.isSucceeded,
                            'workflow-steps__step--failed': step.isFailed,
                            'workflow-steps__step--running': step.isRunning
                        })}>
                        <div
                            className={classNames('workflow-steps__step-circle', {
                                'workflow-steps__step-circle--succeeded': step.isSucceeded,
                                'workflow-steps__step-circle--failed': step.isFailed,
                                'workflow-steps__step-circle--running': step.isRunning
                            })}
                        />
                        <div className='workflow-steps__step-name'>{step.name}</div>
                    </div>
                ))}
            </div>
        </div>
    );
};

// ui/src/app/+workflows/workflows-list-page/workflow-steps/workflow-steps.component.ts
import { Component, Input } from '@angular/core';

import * as models from '../../../models';
import { Workflow, NODE_PHASE } from '../../../models';

@Component({
  selector: 'ax-workflow-steps',
  templateUrl: './workflow-steps.component.html',
  styleUrls: ['./workflow-steps.component.scss']
})
export class WorkflowStepsComponent {

  private _workflow: Workflow;

  public steps: { isSucceeded: boolean; isFailed: boolean; isRunning: boolean; name: string } [] = [];

  @Input()
  public set workflow(val: models.Workflow) {
    this._workflow = val;
    if (val) {
      const entryPointTemplate = val.spec.templates.find(template => template.name === val.spec.entrypoint);
      const phase = this._workflow.status && this._workflow.status.phase;
      let isSucceeded = false;
      let isFailed = false;
      let isRunning = false;
      if (phase === NODE_PHASE.RUNNING) {
        isRunning = true;
      } else {
        isSucceeded = phase === NODE_PHASE.SUCCEEDED;
        isFailed = !isSucceeded;
      }
      this.steps = (entryPointTemplate.steps || []).map(
        group => group[0]).map(step => ({ name: step.name, isSucceeded, isFailed, isRunning }));
    } else {
      this.steps = [];
    }
  }

  public get workflow(): models.Workflow {
    return this._workflow;
  }
}

<div class="workflow-steps">
    <div class="workflow-steps__title">
        <div class="workflow-steps__icon">
            <i class="ax-icon-job" aria-hidden="true"></i>
        </div>
        <div class="workflow-steps__description">
            <div class="workflow-steps__description-title">{{ workflow.metadata.name }}</div>
        </div>
    </div>
    <div class="workflow-steps__timeline">
        <div class="workflow-steps__step-dots">
            <div class="workflow-steps__step-circle workflow-steps__step-circle-small"></div>
            <div class="workflow-steps__step-circle workflow-steps__step-circle-small"></div>
            <div class="workflow-steps__step-circle workflow-steps__step-circle-small"></div>
            <div class="workflow-steps__step-name">&nbsp;</div>
        </div>
        <div *ngFor="let step of (steps ? steps.slice(0, 3) : []); let i = index" class="workflow-steps__step"
             [ngClass]="{
                       'workflow-steps__step--succeeded': step.isSucceeded,
                       'workflow-steps__step--failed': step.isFailed,
                       'workflow-steps__step--running': step.isRunning}">
            <div class="workflow-steps__step-circle" [ngClass]="{
                       'workflow-steps__step-circle--succeeded': step.isSucceeded,
                       'workflow-steps__step-circle--failed': step.isFailed,
                       'workflow-steps__step-circle--running': step.isRunning}"></div>
            <div class="workflow-steps__step-name">{{step.name | truncateTo: 25}}</div>
        </div>
    </div>
</div>
