// saas/axops/src/ui/src/app/views/+help/help.component.ts
import { Component, OnInit } from '@angular/core';
import { SystemService, ContentService, DocUrls } from '../../services';
import { VersionInfo } from '../../model';

@Component({
    selector: 'ax-help',
    templateUrl: './help.component.html',
    styles: [ require('./help.component.scss') ],
})
export class HelpComponent implements OnInit {

    public versionInfo: VersionInfo;
    public docUrls: DocUrls;

    constructor(private systemService: SystemService, private contentService: ContentService) {
    }

    public ngOnInit() {
        this.systemService.getVersion().subscribe(versionInfo => this.versionInfo = versionInfo);
        this.contentService.getDocUrls().then(urls => this.docUrls = urls);
    }
}

<div class="content">
    <div class="row">
        <div class="columns large-4 medium-12">
            <div class="help-box">
                <div class="help-box__ico help-box__ico--manual"></div>
                <h3>Documentation</h3>
                <a href="https://argoproj.io/" target="_blank" class="help-box__link"> Argo Project</a>
            </div>
        </div>
        <div class="columns large-4 medium-12">
            <div class="help-box">
                <div class="help-box__ico help-box__ico--email"></div>
                <h3>Contact</h3>
                <a class="help-box__link" href="https://groups.google.com/forum/#!forum/argo-project">Argo Community</a>
                <a class="help-box__link" href="mailto:support@applatix.com">support@applatix.com</a>
            </div>
        </div>
        <div class="columns large-4 medium-12">
            <div class="help-box">
                <div class="help-box__ico help-box__ico--download"></div>
                <h3>Argo CLI</h3>
                <div class="row text-left help-box__download">
                    <div class="columns small-6">
                        <a href="files/argocli/docker/argo.sh">
                            <i class="docker-logo help-box__docker-logo"></i> Docker
                        </a><br>
                        <a href="files/argocli/linux_amd64/argo"><i
                                class="fa fa-linux" aria-hidden="true"></i> Linux
                        </a>
                    </div>
                    <div class="columns small-6">
                        <a href="files/argocli/darwin_amd64/argo"><i
                                class="fa fa-apple" aria-hidden="true"></i> macOS
                        </a><br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// ui/src/app/help/components/help.tsx
import {Page} from 'argo-ui';
import * as React from 'react';
import {uiUrl} from '../../shared/base';

require('./help.scss');

export const Help = () => (
    <Page title='Help'>
        <div className='row'>
            <div className='columns large-4 medium-12'>
                <div className='help-box'>
                    <div className='help-box__ico help-box__ico--manual' />
                    <h3>Documentation</h3>
                    <a href='https://argoproj.github.io/argo' target='_blank' className='help-box__link'>
                        Online Help
                    </a>
                    <a className='help-box__link' target='_blank' href={uiUrl('/apidocs')}>
                        API Docs
                    </a>
                </div>
            </div>
            <div className='columns large-4 medium-12'>
                <div className='help-box'>
                    <div className='help-box__ico help-box__ico--email' />
                    <h3>Contact</h3>
                    <a className='help-box__link' target='_blank' href='https://argoproj.slack.com'>
                        Slack
                    </a>
                </div>
            </div>
            <div className='columns large-4 medium-12'>
                <div className='help-box'>
                    <div className='help-box__ico help-box__ico--download' />
                    <h3>Argo CLI</h3>
                    <a className='help-box__link' target='_blank' href='https://github.com/argoproj/argo-workflows/releases/latest'>
                        Releases
                    </a>
                </div>
            </div>
        </div>
    </Page>
);
