// ui/src/app/+help/help.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'ax-help',
    templateUrl: './help.component.html',
    styleUrls: [ './help.component.scss' ],
})
export class HelpComponent {
}

<div class="content">
    <div class="row">
        <div class="columns large-4 medium-12">
            <div class="help-box">
                <div class="help-box__ico help-box__ico--manual"></div>
                <h3>Documentation</h3>
                <a href="https://www.argoproj.io/" target="_blank" class="help-box__link"> Argo Project</a>
            </div>
        </div>
        <div class="columns large-4 medium-12">
            <div class="help-box">
                <div class="help-box__ico help-box__ico--email"></div>
                <h3>Contact</h3>
                <a class="help-box__link" href="https://groups.google.com/forum/#!forum/argo-project">Argo Community</a>
                <a class="help-box__link" href="mailto:support@applatix.com">support@applatix.com</a>
            </div>
        </div>
        <div class="columns large-4 medium-12">
            <div class="help-box">
                <div class="help-box__ico help-box__ico--download"></div>
                <h3>Argo CLI</h3>
                <div class="row text-left help-box__download">
                    <div class="columns small-6">
                        <a href="files/argocli/docker/argo.sh">
                            <i class="docker-logo help-box__docker-logo"></i> Docker
                        </a><br>
                        <a href="https://s3-us-west-1.amazonaws.com/ax-public/argocli/stable/linux_amd64/argo"><i
                                class="fa fa-linux" aria-hidden="true"></i> Linux
                        </a>
                    </div>
                    <div class="columns small-6">
                        <a href="https://s3-us-west-1.amazonaws.com/ax-public/argocli/stable/darwin_amd64/argo"><i
                                class="fa fa-apple" aria-hidden="true"></i> macOS
                        </a><br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// ui/src/help/help.tsx
import {Page} from 'argo-ui/src/components/page/page';
import * as React from 'react';

import {useCollectEvent} from '../shared/use-collect-event';

import './help.scss';

export function Help() {
    useCollectEvent('openedHelp');
    return (
        <Page title='Help'>
            <div className='row'>
                <div className='columns large-4 medium-12'>
                    <div className='help-box'>
                        <div className='help-box__ico help-box__ico--manual' />
                        <h3>Documentation</h3>
                        <a className='help-box__link' target='_blank' href='https://argo-workflows.readthedocs.io/en/latest' rel='noreferrer'>
                            Online Help
                        </a>
                        <a className='help-box__link' target='_blank' href='https://argo-workflows.readthedocs.io/en/latest/swagger/' rel='noreferrer'>
                            API Docs
                        </a>
                    </div>
                </div>
                <div className='columns large-4 medium-12'>
                    <div className='help-box'>
                        <div className='help-box__ico help-box__ico--email' />
                        <h3>Contact</h3>
                        <a className='help-box__link' target='_blank' href='https://argoproj.github.io/community/join-slack/' rel='noreferrer'>
                            Slack
                        </a>
                    </div>
                </div>
                <div className='columns large-4 medium-12'>
                    <div className='help-box'>
                        <div className='help-box__ico help-box__ico--download' />
                        <h3>Argo CLI</h3>
                        <a className='help-box__link' target='_blank' href='https://github.com/argoproj/argo-workflows/releases/latest' rel='noreferrer'>
                            Releases
                        </a>
                    </div>
                </div>
            </div>
        </Page>
    );
}
